#!/usr/bin/env bash

echo 'Deprecated.  Please use "codenode-admin backend -devel"'
export PYTHONPATH=$PWD/..
export DJANGO_SETTINGS_MODULE='frontend.settings'
cd env
twistd -n --pidfile=./backend.pid codenode-backend --env_path=$PWD --devel_mode
